name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.name "mireiaparra"
          git config --global user.email "mirmalparra@gmail.com"

      - name: Install
        run: npm ci

      - name: Build 
        run: npm run build 

      - name: Deploy 
        run: npm run deploy -- -r git@github.com:mireiaparra/angular-layout.git
